#!/bin/bash
. /.denv
if [[ "$BIND9" == 1 ]]; then
  echo "bind9 enabled, start"
  cd /etc/bind
  export DOLLAR='$'
  for template in *.template; do
      [ -f "$template" ] || continue
      conf=${template::-9}
      cat $template | sed -e 's/\${/＄/g' | sed 's/\$/${DOLLAR}/g' | sed 's/＄/${/g' | envsubst > $conf
  done
  exec named -g -c /etc/bind/named.conf
else
  echo "bind9 not enabled, down"
  sv down bind9
  exec sleep infinity
fi
