#!/bin/bash
. /.denv

export DOLLAR='$'
cd /etc/wireguard
for template in *.template; do
    [ -f "$template" ] || continue
    conf=${template::-9}
    cat $template | sed -e 's/\${/＄/g' | sed 's/\$/${DOLLAR}/g' | sed 's/＄/${/g' | envsubst > $conf
done

if [[ "$WGCF" == 1 ]]; then
  echo "wgcf enabled"
  ip link add dev wgcf type wireguard
  wg setconf wgcf /etc/wireguard/wgcf.conf
  ip link set wgcf up
  ip link set mtu $WGCF_MTU dev wgcf
  if [[ "$WGCF4" == 1 ]]; then
    echo "wgcf ipv4 enabled"
    ip addr add $WGCF_IPV4 dev wgcf
    ip route replace default dev wgcf
  fi
  if [[ "$WGCF6" == 1 ]]; then
    echo "wgcf ipv6 enabled"
    ip -6 addr add $WGCF_IPV6 dev wgcf
    ip -6 route replace default dev wgcf
  fi
else
  echo "wgcf not enabled, down"
  sv down wgcf
  exec sleep infinity
fi
