#!/bin/bash
. /.denv
delay="$1"
if [[ "$delay" == "now" ]] || [[ "$delay" == "" ]]; then
    delay=0
fi
echo "Reboot after $delay seconds"
sleep $delay
boot_on.sh &
boot_on_pid=$!
sleep 1
kill 1 || kill $boot_on_pid
